### ISSUE TITLE
Session.RunAsync should support Cancelling

### ISSUE THREAD

**Issue by HassanHashemi** [neo4j/neo4j-dotnet-driver#254]
it seems that[ Session.RunAsync(..) ](https://github.com/neo4j/neo4j-dotnet-driver/blob/1.5/Neo4j.Driver/Neo4j.Driver/V1/ISession.cs)dose not support cancelling which is necessary in some cases.

**Comment by technige** [comment]
Hi @HassanHashemi 

Could you clarify whether your expectation here is cancellation of an active transaction or discarding the remainder of a result stream, after some records have been consumed.

**Comment by HassanHashemi** [comment]
@technige Both of what you said makes sense, Though i am aware that first one requires more server side logic.

The fact is that some Neo4j queries are just slow and there is really no way to improve them, So at least being able to cancel it is a great feature.

**Comment by btull89** [comment]
+1 
Typically all async methods should support cancellation tokens. This allows the user or api client to cancel the request on a long running query. This also helps when restarting instances of microservices when a long running query may be blocking a restart.

Since this issue has been closed should I open another issue for this feature?

**Comment by AndyHeap-NeoTech** [comment]
Hi @btull89. Because we write and maintain drivers across several languages there has traditionally been a requirement to try and have a degree of uniformity across the API surfaces. I believe this is the original reason for not implementing the cancellation tokens way back when. However we are in early discussions on the possibility of introducing more idiomatic patterns and usages for each language and the best way to do that. This would certainly be a good candidate that we would consider. We'd have to analyse it more, as it might be one of the bigger changes due to the way the driver is structured/designed. Please feel free to open another issue requesting this feature and I'll make sure to add it to our Future board for more in depth discussion and analysis.

**Comment by btull89** [comment]
Thank you @AndyHeap-NeoTech ! I will open up a feature request.

Also, I'm happy to hear that you are considering introducing more idiomatic patterns and usages for each language! There is a lot of boilerplate code that can be removed if that approach was taken.
