### ISSUE TITLE
Design question: Stream and Linq?

### ISSUE THREAD

**Issue by xied75** [neo4j/neo4j-dotnet-driver#318]
Per the documentation:

> result.First(); // Bruce Wayne
result.First(); // Selina Kyle as you already consumed the previous "first" record!

We do understand that if the Result was supposed to be treated like a __Stream__, in that you can consume parts when it's ready without needing to wait the whole thing materialized from wire; also each part can only be consumed once, (without Seeking of cause).

But doing Linq on this Stream is a bit worrying. We have been educated over the years, that Linq statement normally "defer"/"lazy" on execution, so one could keep on building/chain it, until the materialization point, i.e. iterate over it, or those ToList() methods.

At any other context, code snippet
```csharp
var r1 = result.First();
var r2 = result.First();
```
would imply in fact r1 equals to r2, they hold the same "query" thus data.

What this actually should be is:
```csharp
var r1 = result.GetNext();
var r2 = result.GetNext();
```
(Or use the MoveNext pattern)

So I wonder if this is something that can be improved/clarified?

**Comment by zhenlineo** [comment]
Hi @xied75,
Thanks for your feedback, the reason to settle down on this API was a balance between convenience and correctness.

We thought of just implementing `IEnumerator<T>`:
```
while( result.MoveNext() )
{
    var record = result.Current;
    // do something
}
```
But also we greedily want to have great `Linq` methods for free if we implements `IEnumerable<IRecord>`. Then we end up implementing `IEnumerable<IRecord>`.

In most cases, especially only one iteration of the stream is needed, it works pretty okay. Thus we decided let's try this and document strange behaviour to use Linq with Streaming such as `First`.

Then for the cases where multiple iteration is needed, we can also use Linq's `List` method to save the stream into a list.

Thanks again for letting us know your thoughts about our API. We will think more about using the suggested use pattern of `Linq` in our next API design.

Cheers,
Zhen

**Comment by ali-ince** [comment]
Hi @xied75,

Since our `IStatementResult` is defined as a stream of records, rather than a collection of them - as you're already aware of - creates enumerators over a changing record set. Exposing the result stream with an `IEnumerable` brings in better integrity with the existing language features which drove us to that decision.

Returning consistent results across `IEnumerable` calls, like in supporting multiple enumerations, we need to buffer all the records internally which both requires extra resources and also increases the code complexity. However, it is perfectly valid for the user to explicitly convert the `IEnumerable` into a `ICollection` and do any number of enumerations afterwards, depending on his own use case.

On another side note, our async API returns instances of `IStatementResultCursor` which exposes a cursor-like behaviour - which I guess conforms to your expectations.

We may come up with an improved API in a future major version, and will keep your suggestions in mind as @zhenlineo already stated.

Thanks.

Ali

**Comment by xied75** [comment]
@zhenlineo @ali-ince Thanks for the reply. Just want to repeat, what I was concerned, is more on the "correct abstraction", especially around what 99% C# programmers believe or understand. If an abstraction is bent too much, it might not be suitable at all. This is really where the difficulty lies in API design.

Thanks for the good work, keep going... 👍

**Comment by aviatrix** [comment]
Hey All, 

I just got started with neo4j and the C# driver, and i must say I am baffled and confused by this design choice. 
Why would a simple `.Count()` discard all the entries of a result? 
Why would iterating over a `IEnumerable` discard all the results by default?
This behaviour mimics quantum physics in a way... you changethe state by simply observing it. 

Now.. all is made clear when it's explained WHY this is the case ( treating the results as a stream) but it's pretty counter intuitive. 
Wouldn't support for 2 types of APIs be less confusing, even if one is simply a wrapper around the streams that does `.ToArray()` ?
