### ISSUE TITLE
Namespaces and internals

### ISSUE THREAD

**Issue by IngvarKofoed** [neo4j/neo4j-dotnet-driver#38]
The things below are just my opinion, but I hope you will read it and think about it :) Also I apologies for creating this as an issue, but this is the only way on Github.

I think you should think more about which types are internal and which are public. Only make types public if the client of the code needs to know about them. Examples of types that currently are public but maybe should be internal: `Node, Path, ByteExtensions, CollectionExtensions, Throw` and there is a lot more.

I also think you should think more about the use of namespace. Example: The type `Neo4jException` is something that most of the clients of the Neo4j driver should care about, so having this type in a sub namespace just creates more work to the user of the Neo4j driver. So I think that `Neo4jException` should be in the root namespace. This is just one example, there are many more types I think should be moved around.

The namespace `Neo4j.Driver.Internal` hints that types in here are internal, but most of the types are public. So I think they either should be moved or made internal :) The internal namespace should not pop-up in the intellicense when using the Neo4j driver.

If changes are made in this area, the will be compatible breaking and I think they should be included in 1.0.

I you like, I can come up with a suggestion, as a PR, for how I would organise the types in namespaces and which should be public. Just let me know and Ill happy make it ASAP :)

**Comment by zhenlineo** [comment]
Thanks so much for this feedback I actually did not know the use of public/internal is so strict in dotnet.

We initially designed to be:
- The classes that belongs to the public API are the ones in the root namespace, and exception namespace. (all the classes with proper comments)
- The users should not implement or extend any of the public interfaces or classes except `ILogger`.

@cskardon What do you think of this? Is it so strict of using public in dotnet?

**Comment by cskardon** [comment]
There is an argument either way for this, first off - I agree that `Throw` and all the extension method classes should be internal, no-one needs to see them.

The `internal` namespace issue is an interesting one - simply because the name is `internal` it does imply that the types inside will be `internal`. I guess the question is down to intentions, if the types are never meant to be seen by a user of the driver - then - yes - `internal`-ise them, but if internal in this case means 'stuff you don't need to care about, as it's the guts of the driver, but you can use them if you want' then a rename might be in order.

I don't think the intention was to group all the `internal` types by a Namespace... It would make things more complex for all, and be weird. I guess this is likely a hangover from the Java system.

There is no strict public/internal rule, there are guidelines, but those are really derived from what you want a user to see.

I think @IngvarKofoed is right. By minimising the external footprint of the driver you will save a lot of ache with managing support and you can always bring in new things (`Node` for example if you go the route of an ORM) but you can't take them away.

**Comment by IngvarKofoed** [comment]
Yes I agree with @cskardon that the most important thing is minimising the external footprint by using the `internal` keyword. 

Regarding namespaces, I also think that they are not for whats internal and whats not internal. Namespaces are for grouping common types together and as a good guideline, the deeper the namespace (more dots) the more complex the types/code is. The idea behind this guideline is that developers using a library will first see the types in the root namespace.

Should I create PR? :)

**Comment by zhenlineo** [comment]
Alright. It would be interesting to know how you would like to restruct the driver.

**Comment by IngvarKofoed** [comment]
Cool! Ill make a PR later today with a suggestion on how to I would do it :)

**Comment by IngvarKofoed** [comment]
You can see my suggestion here: https://github.com/IngvarKofoed/neo4j-dotnet-driver/tree/1.0-internaling-types

I could not internal the BaseLogger and thats something I think needs to be fixed. I think the BaseLogger should not be inherited, but called (changing from composition to aggregation).

I removed the Internal from the root namespace because i do not think it makes much sense. Using the word internal should be in a sub namespace if needed - if you ask me :)

What do you think?

**Comment by IngvarKofoed** [comment]
Also, I could not find the type `IIdentity`, but it was listed on the documentation site. Is this a problem?

**Comment by IngvarKofoed** [comment]
For 1.0 I think we should take only this commit: https://github.com/IngvarKofoed/neo4j-dotnet-driver/commit/93c3ccfa017ee6f2b78196136081b34e867743fe

The commit where all non public types are made internal with the internal keyword and Neo4j exceptions are moved to root namespace for easy usage. This will ensure that no non-public types are used/inherited by client code. This is important because those types, if changed, will most likely break existing client code (bad user experience). So I think this is important for 1.0 :)

I can make a PR for this if you agree?

**Comment by IngvarKofoed** [comment]
PR #53 created :)

**Comment by zhenlineo** [comment]
I moved LoggerBase from Driver in https://github.com/neo4j/neo4j-dotnet-driver/pull/54/commits/12d81b0b2f5380f18bbf6d47361837d111187e57

**Comment by zhenlineo** [comment]
Closing this as the PR #54 get merged. Moving to revisit the public API docs soon.
