### ISSUE TITLE
Parallel tasks writing merge statements create duplicate nodes

### ISSUE THREAD

**Issue by MPasadu** [neo4j/neo4j-dotnet-driver#412]
- Neo4j version: Neo4j Server version: 4.0.0 (community)
- Neo4j Mode: Single instance
- Driver version: .net driver 4.0.1
- Operating system: Windows 10 Pro, Docker

I was playing around with parallel tasks. Using something akin to the following code:

```
foreach (var testString in new List<string>{ "1", "2", "3" }) // actually a very big list of strings
{
       tasks.Add(Task.Run(() => 
       {
               var session = _neo4J.Driver.AsyncSession(o => o.WithDatabase("neo4j"));
               var cursor = await session.RunAsync(
                    @"merge
                                (current:Test {value:$Test })
                     merge
                                (parent:Test {value:"0"})
                     merge
                                (parent)-[:HAS_CHILD]->(current)",
                    new
                    {
                        Test = testString,
                    });
               await cursor.ConsumeAsync();
       }));
}
```

Which results in a lot of :Test nodes being duplicates with the same value property. I think this is to be expected because sessions and transactions are not thread-safe? But what is the recommended approach? In a multi-threaded application couldn't this always happen?

**Comment by AndyHeap-NeoTech** [comment]
Hi MPasadu. You are correct in thinking that this is the expected behaviour. Because the multiple merge statements are each being run in a new session they are in separate transactions and the server will be running them in parallel. This means that the ordering/timing of the merges is not guaranteed and you will see the results that you are getting.  To successfully run the merges you would want to do them in a single session, using either a single transaction or chaining several together should it be needed.
