### ISSUE TITLE
Driver cannot handle Guid values

### ISSUE THREAD

**Issue by simon-hardy** [neo4j/neo4j-dotnet-driver#71]
Version used: 1.0.0

Error message:

> Cannot understandvalue with type System.Guid
> Parameter name: value
> Actual value was System.Guid.

Easiest way to replicate:

`txn.Run("CREATE (person:Person {name: {name}})", new Dictionary<string, object> { { "name", Guid.NewGuid() } });`

**Comment by technige** [comment]
Guid is not a valid Neo4j type. You will have to convert this to a string to be able to store it.

**Comment by simon-hardy** [comment]
Should that not be the responsibility of the driver? 

Seems like something everyone would want or expect to me.

For comparison, Neo4jClient already handles this type conversion implicitly.

**Comment by zhenlineo** [comment]
Thank you very much for this suggestion. We currently just support the basic types that Cypher supports. The mapping between the Cypher types and the language native types could be found in the [driver doc](http://neo4j.com/docs/developer-manual/3.0/index.html#types). The legal types for the generic type used in List and Dictionary are the language types that understand by Cypher types, e.g.

```
new Dictionary<string, object> { {
    "name", 
    new Dictionary<string, object> { { "first", "Onion"  }, { "surname", "Knight" } }
} }
```

The reason that we did not add other widely-used types such as guid, date, etc. in this driver is that they are so general and important that we _might_ want to support them in Cypher directly. So in this driver we do not want to make any assumption how we would map them in current Cypher types but to reserve these language types (Guid, DateTime) for possible future Cypher types.

I totally understand your need to easily use these additional types, however for this driver, we would like to reserve them for now. We would appreciate if anyone would like to build some extension methods or structure to handle the Guid and DateTime type conversion implicitly in another project. But for this driver, we will not consider this missing support for Guid/DateTime value as a bug for now.

Pls let us know if you have other concerns for supporting Guid or Date types, otherwise I would close this and other Date issue #72 for now.
