### ISSUE TITLE
 "The Neo4j Server doesn't support this client."

### ISSUE THREAD

**Issue by malclear** [neo4j/neo4j-dotnet-driver#75]
I'm getting an error when trying to connect: "The Neo4j Server doesn't support this client." Debugging through the Neo4j.Driver code, I see the 'DoHandshake()' call to the TCPSocketClient is returning version value of "1213486160" instead of the expected "1".
I am using
-  Neo4J-CE, version 3.0.0. 
- Neo4j.Server, version 1.0.0
- Windows 10 Pro, 64-bit

**Comment by zhenlineo** [comment]
Aha, my collea told me that you get this error probably because you are trying to connect to the HTTP endpoint rather than the bolt endpoint. Are you using `bolt://localhost:7474`? 

If so, please try `bolt://localhost:7687` instead. To use the driver, you should connect to the bolt endpoint. a.k.a. `bolt://localhost:7687` or just leave it to be `bolt://localhost`

**Comment by malclear** [comment]
This is correct. I have it working now.
Thank you.
