### ISSUE TITLE
Any plans on async operations?

### ISSUE THREAD

**Issue by drgraduss** [neo4j/neo4j-dotnet-driver#81]
I wonder if there are any plans implementing async operations like `session.RunAsync(..)` etc.

**Comment by zhenlineo** [comment]
Not yet. Async might require some protocol changes too. But we are not in that far at this moment. It is a good to have feature for sure.

**Comment by drgraduss** [comment]
@zhenlineo  thanks for reply!

**Comment by zmarty** [comment]
I don't think this item should have been closed. Good to have is an understatement. Async support is vital for web applications.

**Comment by technige** [comment]
We do expect to introduce an async API across the official drivers at some point but have no firm date on doing so as yet.

Closing this issue has no bearing on that deliverable though as this will be a feature extended across all drivers, not just .NET.

**Comment by fsimonazzi** [comment]
Any updates on this? Not having an async/non-blocking way to access the database is a deal breaker for server-side implementations.

**Comment by zmarty** [comment]
I again respectfully ask for this item to be re-opened. It does not matter if the work will be done, the item should be kept open until it is fixed.

**Comment by technige** [comment]
I can confirm that we still have this on our long term roadmap but as yet, we cannot give any timescales.

Please do not see the status of this particular issue as in any way bound to feature delivery. This issue was closed for internal workflow reasons and general async operations will be implemented more broadly than just as a facet of the .NET driver.
