### ISSUE TITLE
Stream results of Session.Run() instead of preloading them all

### ISSUE THREAD

**Issue by shift-evgeny** [neo4j/neo4j-dotnet-driver#86]
When running `session.Run("MATCH (n) RETURN n")` the driver seems to preload all results into memory before returning any of them. Even without the high memory usage (#85) this would make it impractical for working with many rows. I would expect `Run()` to return as soon as the first result is available and then load the results from the server as the caller enumerates over the returned `IStatementResult`, similar to how `SqlCommand.ExecuteReader()` works. (If there are reasons to preload results in some cases then perhaps there can be a separate methods for streaming and preloading results.)

**Comment by zhenlineo** [comment]
Yeah, it is a know bug in this driver, which we did streaming wrongly. It ends up with not streaming at all. We will try to fix this bug in the coming release.

Regarding the memory opt #85, this is indeed a good start point.

**Comment by zhenlineo** [comment]
We brought streaming into 1.1 instead of 1.0 driver. 1.1.0-M01 is released recently with the first step towards streaming results [#96](https://github.com/neo4j/neo4j-dotnet-driver/pull/96) in. The follow-up work is [#97](https://github.com/neo4j/neo4j-dotnet-driver/pull/97) where unconsumed records would be buffered. 

The current behaviour is almost the same as what you have suggested. `Run()` will return immediately when the server has confirmed that the statement is received (the message before the first record/row arrives), and enumerating over the result will pull the records slowly from the underlying socket buffer. 

If we always consume our result, then we always streaming records. However buffering will kick in if a result is not fully consumed (#97).

**Comment by zhenlineo** [comment]
The new release 1.1.0-M02 includes the completed streaming. Please be free to test it out. With the new streaming, you would probably not see an error until you starts to consuming the result. When we call session.run, the cypher statement is send to server to run, however the reply comes back but will not be consumed/throw to a client until the client starts to iterating on the result comes back.

I am closing this issue, but you are always most welcome to give us more feedback on this new feature in another issue.
